// CarsList.js
import React from "react";
import CarListing from "../CarListing/CarListing";  // Make sure this path is correct
import "../CarsList/CarsList.css";

const CarsList = () => {
    const carsData = [
        {
          image: "./img/couple-near-new-white-car-man-driving-work-his-wife-will-waiting-him.jpg",
          year: 2022,
          make: "Toyota",
          model: "Camry",
          price: 24999,
          mileage: 20000,
          engine: "2.5L 4-cylinder",
          transmission: "Automatic",
          fuelType: "Gasoline",
          driveType: "FWD",
          mpg: "28 city / 39 highway",
          features: ["Lane Departure Warning", "Adaptive Cruise Control", "Backup Camera"],
        },
        {
          image: "./img/yellow-sport-car-with-black-autotuning-high-speed-drive.jpg",
          year: 2021,
          make: "Honda",
          model: "Civic",
          price: 21999,
          mileage: 15000,
          engine: "2.0L 4-cylinder",
          transmission: "Manual",
          fuelType: "Gasoline",
          driveType: "FWD",
          mpg: "30 city / 38 highway",
          features: ["Bluetooth Connectivity", "Backup Camera", "Heated Seats"],
        },
        {
          image: "./img/gray-suv-is-parked-road-front-field.jpg",
          year: 2023,
          make: "Ford",
          model: "Escape",
          price: 28999,
          mileage: 12000,
          engine: "1.5L Turbocharged",
          transmission: "Automatic",
          fuelType: "Gasoline",
          driveType: "AWD",
          mpg: "23 city / 31 highway",
          features: ["Blind Spot Monitoring", "Lane Keeping Assist", "Navigation System"],
        },
        {
          image: "./img/3d-car-vibrant-city-night.jpg",
          year: 2020,
          make: "Chevrolet",
          model: "Corvette",
          price: 59999,
          mileage: 5000,
          engine: "6.2L V8",
          transmission: "Manual",
          fuelType: "Gasoline",
          driveType: "RWD",
          mpg: "15 city / 22 highway",
          features: ["Leather Seats", "Bose Sound System", "Heated Seats"],
        },
        {
          image: "./img/yellow-car-gas-station.jpg",
          year: 2022,
          make: "BMW",
          model: "5 Series",
          price: 52999,
          mileage: 18000,
          engine: "2.0L 4-cylinder Turbocharged",
          transmission: "Automatic",
          fuelType: "Gasoline",
          driveType: "AWD",
          mpg: "25 city / 34 highway",
          features: ["Apple CarPlay", "Panoramic Sunroof", "Surround-View Camera"],
        },
        {
          image: "./img/photorealistic-view-off-road-car-with-nature-terrain-weather-conditions.jpg",
          year: 2022,
          make: "Jeep",
          model: "Cherokee",
          price: 35999,
          mileage: 8000,
          engine: "3.2L V6",
          transmission: "Automatic",
          fuelType: "Gasoline",
          driveType: "4WD",
          mpg: "22 city / 31 highway",
          features: ["Heated Steering Wheel", "Navigation", "Rearview Camera"],
        },
        {
          image: "./img/high-speed-test-driving-white-sport-car.jpg",
          year: 2023,
          make: "Toyota",
          model: "Prius",
          price: 24999,
          mileage: 10000,
          engine: "1.8L 4-cylinder Hybrid",
          transmission: "CVT",
          fuelType: "Hybrid",
          driveType: "FWD",
          mpg: "54 city / 50 highway",
          features: ["Adaptive Cruise Control", "Lane Tracing Assist", "Touchscreen Display"],
        },
        {
          image: "./img/low-angle-white-modern-car-outdoors.jpg",
          year: 2021,
          make: "Ram",
          model: "1500",
          price: 39999,
          mileage: 25000,
          engine: "5.7L V8",
          transmission: "Automatic",
          fuelType: "Gasoline",
          driveType: "4WD",
          mpg: "15 city / 22 highway",
          features: ["Tow Package", "Leather Seats", "Apple CarPlay"],
        },
        {
          image: "./img/car-with-simple-background.jpg",
          year: 2023,
          make: "Tesla",
          model: "Model 3",
          price: 46999,
          mileage: 1500,
          engine: "Electric",
          transmission: "Automatic",
          fuelType: "Electric",
          driveType: "AWD",
          mpg: "148 MPGe city / 132 MPGe highway",
          features: ["Autopilot", "Touchscreen Interface", "Premium Audio"],
        },
        {
          image: "./img/man-parked-side-road.jpg",
          year: 2020,
          make: "Nissan",
          model: "Rogue",
          price: 23999,
          mileage: 22000,
          engine: "2.5L 4-cylinder",
          transmission: "Automatic",
          fuelType: "Gasoline",
          driveType: "AWD",
          mpg: "26 city / 33 highway",
          features: ["Blind Spot Monitoring", "Remote Start", "Apple CarPlay"],
        },
      ];
      

  return (
    <div className="cars-list">
      {carsData.map((car, index) => (
        <CarListing key={index} car={car} />
      ))}
    </div>
  );
};

export default CarsList;
